# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\image_search_bing\main_front.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import main_back as fns


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 751, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.le_search = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_search.setObjectName("le_search")
        self.mainVLayout.addWidget(self.le_search)
        self.scrArea_search_result_images = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrArea_search_result_images.setWidgetResizable(True)
        self.scrArea_search_result_images.setObjectName("scrArea_search_result_images")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 747, 503))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrArea_search_result_images.setWidget(self.scrollAreaWidgetContents)
        self.gridLayoutForScrArea = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        
        self.mainVLayout.addWidget(self.scrArea_search_result_images)
        self.btnHlayout = QtWidgets.QHBoxLayout()
        self.btnHlayout.setObjectName("btnHlayout")
        self.btn_search = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_search.setObjectName("btn_search")
        self.btn_search.clicked.connect(self.search)

        self.btnHlayout.addWidget(self.btn_search)
        self.btn_clear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_clear.clicked.connect(self.clear_page)

        self.btnHlayout.addWidget(self.btn_clear)
        self.btn_exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_exit.setObjectName("btn_exit")
        self.btn_exit.clicked.connect(self.close)

        self.btnHlayout.addWidget(self.btn_exit)
        self.mainVLayout.addLayout(self.btnHlayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def search(self):
        """Searches for images"""
        self.clear_scroll_area()
        search_term = self.le_search.text()
        if not search_term == '':
            linkes = fns.get_list_of_images(search_term)
            for i, link in enumerate(linkes):
                binary = fns.get_image_content(link)
                if binary is not None:
                    pixmap1 = QtGui.QPixmap()
                    pixmap1.loadFromData(binary)
                    lbl = QtWidgets.QLabel()
                    lbl.setPixmap(pixmap1)
                    self.gridLayoutForScrArea.addWidget(lbl, i // 3, i % 3)
                    print('done')
                else:
                    print('empty link')
        print('all done', end='\n\n')
            
    def clear_page(self):
        """Clears all of the page"""
        self.clear_scroll_area()
        self.le_search.clear()

    def clear_scroll_area(self):
        """Clears the scroll area"""
        for i in reversed(range(self.scrollAreaWidgetContents.layout().count())):
            self.scrollAreaWidgetContents.layout().itemAt(i).widget().setParent(None)

    def close(self):
        """Closes the app"""
        sys.exit()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
